<template>
    <div>
        <!--菜单-->
        <Menus/>
        <div id="module_10900" data-spm="10900" data-name="zc-complete-rank" data-group="abs-mod" data-version="1.1.32" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
            <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
                <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 0px; background-color: white;"></div>
                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; justify-content: center; height: 44px; line-height: 44px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; width: 375px;">
                        <div style="border-width: 0px 0px 2px; border-style: solid; border-color: black black rgb(2, 194, 201); position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex: 1 1 0%; -webkit-box-flex: 1; text-align: center; font-size: 14px; padding-bottom: 2px; color: rgb(2, 194, 201); height: 44px; font-weight: bold; background-color: rgb(255, 255, 255);">
                            <span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 14px;">综合排名</span></div>
                        <div
                            style="border-width: 0px 0px 1px; border-style: solid; border-color: black black rgb(224, 224, 224); position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex: 1 1 0%; -webkit-box-flex: 1; text-align: center; font-size: 14px; color: rgb(5, 27, 43); height: 44px; background-color: rgb(255, 255, 255);">
                            <span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 14px;">人气最高</span></div>
                        <div
                            style="border-width: 0px 0px 1px; border-style: solid; border-color: black black rgb(224, 224, 224); position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex: 1 1 0%; -webkit-box-flex: 1; text-align: center; font-size: 14px; color: rgb(5, 27, 43); height: 44px; background-color: rgb(255, 255, 255);">
                            <span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 14px;">金额最高</span></div>
                    </div>
                </div>
                <div id="list" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
                    <!-- empty -->
                    <div>
                        <div>
                            <div style="display: flex; -webkit-box-orient: horizontal; flex-direction: row;">
                                <div style="-webkit-box-flex: 1; flex: 1 1 0%;">
                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
                                        <a style="text-decoration: none; display: flex; width: 375px; height: 125px; -webkit-box-orient: horizontal; flex-direction: row; -webkit-box-pack: justify; justify-content: space-between; position: relative;">
                                            <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 125px; height: 125px;">
                                                <div isonce="1" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 122px; width: 125px; background-image: url(../../assets/list001.webp); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;"></div>
                                            </div>
                                            <div style="border-width: 0px 0px 1px; border-style: solid; border-color: black black rgb(241, 241, 241); position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 239px; height: 125px;">
                                                <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; margin-top: 9.5px; height: 35px; width: 230px; overflow: hidden;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 14px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; width: 230px; line-height: 1.3; color: rgb(51, 51, 51);">欧巴德健身仪，仿生物电流刺激，肌肉训练移动健身房</span></div>
                                                <div
                                                    style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 230px; margin-top: 3px;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 17px; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center;">
                                                        <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 191px; height: 2.5px;">
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(224, 224, 224);"></div>
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(2, 194, 201);"></div>
                                                        </div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 10px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 17px; color: rgb(51, 51, 51);">4847%</span></div>
                                                    <div
                                                        style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 14px; -webkit-box-pack: start; justify-content: flex-start; -webkit-box-align: center; align-items: center;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">12848人支持</span>
                                                        <div
                                                            style="border-width: 0px 1px 0px 0px; border-style: solid; border-color: black rgb(153, 153, 153) black black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 14px; margin: 0px 4px;"></div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">已筹484.7万</span></div>
                                                </div>
                                                <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; bottom: 0px; left: 0px; width: 230px; -webkit-box-pack: justify; justify-content: space-between;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; align-items: baseline;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201);">￥</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 16px; font-weight: bold; line-height: 40px; color: rgb(2, 194, 201); font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif;">99</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); font-weight: bold;">.00</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); margin-left: 2px;">起</span></div>
                                                </div>
                                            </div>
                                            <div isonce="1" style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 36px; width: 36px; top: 0px; left: 0px; background-image: url(https://gw.alicdn.com/tfs/TB1ZdcPOVXXXXcfXFXXXXXXXXXX-72-72.png_110x10000.jpg_.webp); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;"></div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div style="display: flex; -webkit-box-orient: horizontal; flex-direction: row;">
                                <div style="-webkit-box-flex: 1; flex: 1 1 0%;">
                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
                                        <a style="text-decoration: none; display: flex; width: 375px; height: 125px; -webkit-box-orient: horizontal; flex-direction: row; -webkit-box-pack: justify; justify-content: space-between; position: relative;">
                                            <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 125px; height: 125px;">
                                                <div isonce="1" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 122px; width: 125px; background-image: url(https://gw.alicdn.com/tfscom/TB1fkJePFXXXXc2XFXXSutbFXXX_290x10000Q75.jpg_.webp); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;"></div>
                                            </div>
                                            <div style="border-width: 0px 0px 1px; border-style: solid; border-color: black black rgb(241, 241, 241); position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 239px; height: 125px;">
                                                <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; margin-top: 9.5px; height: 35px; width: 230px; overflow: hidden;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 14px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; width: 230px; line-height: 1.3; color: rgb(51, 51, 51);">改变开车陋习——您的智能语音驾驶助手</span></div>
                                                <div
                                                    style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 230px; margin-top: 3px;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 17px; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center;">
                                                        <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 191px; height: 2.5px;">
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(224, 224, 224);"></div>
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(2, 194, 201);"></div>
                                                        </div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 10px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 17px; color: rgb(51, 51, 51);">2521%</span></div>
                                                    <div
                                                        style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 14px; -webkit-box-pack: start; justify-content: flex-start; -webkit-box-align: center; align-items: center;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">18302人支持</span>
                                                        <div
                                                            style="border-width: 0px 1px 0px 0px; border-style: solid; border-color: black rgb(153, 153, 153) black black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 14px; margin: 0px 4px;"></div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">已筹252.1万</span></div>
                                                </div>
                                                <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; bottom: 0px; left: 0px; width: 230px; -webkit-box-pack: justify; justify-content: space-between;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; align-items: baseline;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201);">￥</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 16px; font-weight: bold; line-height: 40px; color: rgb(2, 194, 201); font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif;">99</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); font-weight: bold;">.00</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); margin-left: 2px;">起</span></div>
                                                </div>
                                            </div>
                                            <div isonce="1" style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 36px; width: 36px; top: 0px; left: 0px; background-image: url(https://gw.alicdn.com/tfs/TB15kkSOVXXXXaqXFXXXXXXXXXX-72-72.png_110x10000.jpg_.webp); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;"></div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div style="display: flex; -webkit-box-orient: horizontal; flex-direction: row;">
                                <div style="-webkit-box-flex: 1; flex: 1 1 0%;">
                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
                                        <a style="text-decoration: none; display: flex; width: 375px; height: 125px; -webkit-box-orient: horizontal; flex-direction: row; -webkit-box-pack: justify; justify-content: space-between; position: relative;">
                                            <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 125px; height: 125px;">
                                                <div isonce="1" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 122px; width: 125px; background-image: url(https://gw.alicdn.com/tfscom/TB1yDwfPVXXXXczXFXXSutbFXXX_290x10000Q75.jpg_.webp); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;"></div>
                                            </div>
                                            <div style="border-width: 0px 0px 1px; border-style: solid; border-color: black black rgb(241, 241, 241); position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 239px; height: 125px;">
                                                <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; margin-top: 9.5px; height: 35px; width: 230px; overflow: hidden;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 14px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; width: 230px; line-height: 1.3; color: rgb(51, 51, 51);">艾普莱斯Mini多功能除湿机，处处是晴天</span></div>
                                                <div
                                                    style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 230px; margin-top: 3px;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 17px; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center;">
                                                        <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 191px; height: 2.5px;">
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(224, 224, 224);"></div>
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(2, 194, 201);"></div>
                                                        </div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 10px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 17px; color: rgb(51, 51, 51);">5147%</span></div>
                                                    <div
                                                        style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 14px; -webkit-box-pack: start; justify-content: flex-start; -webkit-box-align: center; align-items: center;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">13787人支持</span>
                                                        <div
                                                            style="border-width: 0px 1px 0px 0px; border-style: solid; border-color: black rgb(153, 153, 153) black black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 14px; margin: 0px 4px;"></div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">已筹514.7万</span></div>
                                                </div>
                                                <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; bottom: 0px; left: 0px; width: 230px; -webkit-box-pack: justify; justify-content: space-between;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; align-items: baseline;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201);">￥</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 16px; font-weight: bold; line-height: 40px; color: rgb(2, 194, 201); font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif;">299</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); font-weight: bold;">.00</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); margin-left: 2px;">起</span></div>
                                                </div>
                                            </div>
                                            <div isonce="1" style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 36px; width: 36px; top: 0px; left: 0px; background-image: url(https://gw.alicdn.com/tfs/TB1haQ5OVXXXXczXXXXXXXXXXXX-72-72.png_110x10000.jpg_.webp); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;"></div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div style="display: flex; -webkit-box-orient: horizontal; flex-direction: row;">
                                <div style="-webkit-box-flex: 1; flex: 1 1 0%;">
                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
                                        <a style="text-decoration: none; display: flex; width: 375px; height: 125px; -webkit-box-orient: horizontal; flex-direction: row; -webkit-box-pack: justify; justify-content: space-between; position: relative;">
                                            <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 125px; height: 125px;">
                                                <div isonce="1" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 122px; width: 125px; background-image: url(https://gw.alicdn.com/tfscom/TB1jM0LPFXXXXb1XpXXSutbFXXX_290x10000Q75.jpg_.webp); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;"></div>
                                            </div>
                                            <div style="border-width: 0px 0px 1px; border-style: solid; border-color: black black rgb(241, 241, 241); position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 239px; height: 125px;">
                                                <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; margin-top: 9.5px; height: 35px; width: 230px; overflow: hidden;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 14px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; width: 230px; line-height: 1.3; color: rgb(51, 51, 51);">追剧神器 欣普飞全平台通用U盘</span></div>
                                                <div
                                                    style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 230px; margin-top: 3px;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 17px; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center;">
                                                        <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 191px; height: 2.5px;">
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(224, 224, 224);"></div>
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(2, 194, 201);"></div>
                                                        </div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 10px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 17px; color: rgb(51, 51, 51);">5300%</span></div>
                                                    <div
                                                        style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 14px; -webkit-box-pack: start; justify-content: flex-start; -webkit-box-align: center; align-items: center;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">29476人支持</span>
                                                        <div
                                                            style="border-width: 0px 1px 0px 0px; border-style: solid; border-color: black rgb(153, 153, 153) black black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 14px; margin: 0px 4px;"></div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">已筹530.0万</span></div>
                                                </div>
                                                <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; bottom: 0px; left: 0px; width: 230px; -webkit-box-pack: justify; justify-content: space-between;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; align-items: baseline;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201);">￥</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 16px; font-weight: bold; line-height: 40px; color: rgb(2, 194, 201); font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif;">99</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); font-weight: bold;">.00</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); margin-left: 2px;">起</span></div>
                                                </div>
                                            </div>
                                            <!-- empty -->
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div style="display: flex; -webkit-box-orient: horizontal; flex-direction: row;">
                                <div style="-webkit-box-flex: 1; flex: 1 1 0%;">
                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
                                        <a style="text-decoration: none; display: flex; width: 375px; height: 125px; -webkit-box-orient: horizontal; flex-direction: row; -webkit-box-pack: justify; justify-content: space-between; position: relative;">
                                            <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 125px; height: 125px;">
                                                <div isonce="1" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 122px; width: 125px; background-image: url(https://gw.alicdn.com/tfscom/TB1gn.JPVXXXXcHapXXSutbFXXX_290x10000Q75.jpg_.webp); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;"></div>
                                            </div>
                                            <div style="border-width: 0px 0px 1px; border-style: solid; border-color: black black rgb(241, 241, 241); position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 239px; height: 125px;">
                                                <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; margin-top: 9.5px; height: 35px; width: 230px; overflow: hidden;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 14px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; width: 230px; line-height: 1.3; color: rgb(51, 51, 51);">大鱼智行车，十公里出行不二之选，轻巧智能</span></div>
                                                <div
                                                    style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 230px; margin-top: 3px;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 17px; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center;">
                                                        <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 191px; height: 2.5px;">
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(224, 224, 224);"></div>
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(2, 194, 201);"></div>
                                                        </div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 10px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 17px; color: rgb(51, 51, 51);">1303%</span></div>
                                                    <div
                                                        style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 14px; -webkit-box-pack: start; justify-content: flex-start; -webkit-box-align: center; align-items: center;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">637人支持</span>
                                                        <div
                                                            style="border-width: 0px 1px 0px 0px; border-style: solid; border-color: black rgb(153, 153, 153) black black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 14px; margin: 0px 4px;"></div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">已筹130.3万</span></div>
                                                </div>
                                                <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; bottom: 0px; left: 0px; width: 230px; -webkit-box-pack: justify; justify-content: space-between;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; align-items: baseline;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201);">￥</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 16px; font-weight: bold; line-height: 40px; color: rgb(2, 194, 201); font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif;">1299</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); font-weight: bold;">.00</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); margin-left: 2px;">起</span></div>
                                                </div>
                                            </div>
                                            <!-- empty -->
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div style="display: flex; -webkit-box-orient: horizontal; flex-direction: row;">
                                <div style="-webkit-box-flex: 1; flex: 1 1 0%;">
                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
                                        <a style="text-decoration: none; display: flex; width: 375px; height: 125px; -webkit-box-orient: horizontal; flex-direction: row; -webkit-box-pack: justify; justify-content: space-between; position: relative;">
                                            <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 125px; height: 125px;">
                                                <div isonce="1" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 122px; width: 125px; background-image: url(https://gw.alicdn.com/tfscom/TB1ZZLYPFXXXXa.XFXXwu0bFXXX_290x10000Q75.jpg_.webp); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;"></div>
                                            </div>
                                            <div style="border-width: 0px 0px 1px; border-style: solid; border-color: black black rgb(241, 241, 241); position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 239px; height: 125px;">
                                                <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; margin-top: 9.5px; height: 35px; width: 230px; overflow: hidden;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 14px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; width: 230px; line-height: 1.3; color: rgb(51, 51, 51);">Elfinbook可重复书写笔记本，App备份管理</span></div>
                                                <div
                                                    style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 230px; margin-top: 3px;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 17px; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center;">
                                                        <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 191px; height: 2.5px;">
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(224, 224, 224);"></div>
                                                            <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(2, 194, 201);"></div>
                                                        </div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 10px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 17px; color: rgb(51, 51, 51);">3744%</span></div>
                                                    <div
                                                        style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 230px; height: 14px; -webkit-box-pack: start; justify-content: flex-start; -webkit-box-align: center; align-items: center;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">13766人支持</span>
                                                        <div
                                                            style="border-width: 0px 1px 0px 0px; border-style: solid; border-color: black rgb(153, 153, 153) black black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 14px; margin: 0px 4px;"></div><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">已筹374.4万</span></div>
                                                </div>
                                                <div style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; bottom: 0px; left: 0px; width: 230px; -webkit-box-pack: justify; justify-content: space-between;">
                                                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; align-items: baseline;"><span style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201);">￥</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 16px; font-weight: bold; line-height: 40px; color: rgb(2, 194, 201); font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif;">19</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); font-weight: bold;">.90</span><span
                                                            style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); margin-left: 2px;">起</span></div>
                                                </div>
                                            </div>
                                            <!-- empty -->
                                        </a>
                                    </div>
                                </div>
                            </div>
                            
                            
                        </div>
                    </div>
                    <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
                        <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;"></div>
                    </div>
                    <!-- empty -->
                </div>
                <div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 17.5px; text-align: center; color: rgb(153, 153, 153); font-size: 12px; line-height: 17.5px; font-family: 'PingFang SC', Helvetica, 'Helvetica Neue', Arial; background-color: rgb(231, 231, 231);">加载中...</div>
            </div>
        </div>
        <!--底部-->
        <Footers/>
    </div>
</template>
<script>
    import Menus from 'components/menu';
    import Footers from 'components/footer';
    export default {
        name: 'list',
        created: () => {
            //这里相当于ready 后执行函数
        },
        components: {
            Menus,Footers
        },
        data() {
            return{
                msg: 'Welcome to js'}
        }
    }

</script>