<template>
    <div data-v-baaae3f0="" style="display: flex; -webkit-box-orient: horizontal; flex-direction: row;">
        <div data-v-baaae3f0="" style="-webkit-box-flex: 1; flex: 1 1 0%;">
            <div data-v-baaae3f0="" data-spm="da0" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
                <a data-v-baaae3f0="" style="text-decoration: none; display: flex; width: 375px; height: 125px; -webkit-box-orient: horizontal; flex-direction: row; -webkit-box-pack: justify; justify-content: space-between;">
                    <div data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 125px; height: 125px;"><img data-v-baaae3f0="" src="../../assets/list001.jpg" style="display: flex; width: 125px; height: 122px; object-fit: cover;"></div>
                    <div data-v-baaae3f0="" style="border-width: 0px 0px 1px; border-style: solid; border-color: black black rgb(241, 241, 241); position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 239px; height: 125px;">
                        <div data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; margin-top: 9.5px; height: 35px; width: 230px; overflow: hidden;"><span data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 14px; width: 230px; line-height: 1.3; color: rgb(51, 51, 51);">博牌隐形安全防盗背包</span></div>
                        <div data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; -webkit-box-pack: start; width: 230px; margin-top: 3px;">
                            <div data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; height: 17px; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center; width: 230px;">
                                <div data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 191px; height: 2.5px;">
                                    <div data-v-baaae3f0="" style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(224, 224, 224);"></div>
                                    <div data-v-baaae3f0="" style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 100%; height: 2.5px; border-radius: 2.5px; background-color: rgb(2, 194, 201);"></div>
                                </div><span data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 10px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; color: rgb(51, 51, 51); line-height: 17px;">195%</span></div>
                            <div data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; height: 14px; -webkit-box-pack: start; justify-content: flex-start; -webkit-box-align: center; align-items: center; width: 230px;"><span data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">395人支持</span>
                                <div data-v-baaae3f0="" style="border-width: 0px 1px 0px 0px; border-style: solid; border-color: black rgb(153, 153, 153) black black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; height: 14px; margin: 0px 4px;"></div><span data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 18px; color: rgb(153, 153, 153);">已筹9.7万</span></div>
                        </div>
                        <div data-v-baaae3f0="" style="border: 0px solid black; position: absolute; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; bottom: 0px; left: 0px; width: 230px; -webkit-box-pack: justify; justify-content: space-between;">
                            <div data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; align-items: baseline;"><span data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-weight: bold; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201);">￥</span><span
                                    data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 16px; font-weight: bold; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201);">199</span><span
                                    data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); font-weight: bold;">.00</span><span
                                    data-v-baaae3f0="" style="border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12px; font-family: 'PingFang SC', 'Helvetica Neue', Helvetica, STHeiTi, sans-serif; line-height: 40px; color: rgb(2, 194, 201); margin-left: 2px;">起</span></div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</template>
<script>
    export default {
        name: 'component-item-overview',
        data() {
            return {}
        }
    }

</script>